language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

env:
  - FB=2.1
  - FB=2.5

# run build against hhvm but allow them to fail
# http://docs.travis-ci.com/user/build-configuration/#Rows-That-are-Allowed-To-Fail
matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: nightly

# faster builds on new travis setup not using sudo
sudo: true

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
  - sudo apt-get update -qq 
  - sudo apt-get install -qq firebird$FB-super firebird$FB-dev expect
  - if [[ "$FB" == "2.1" ]]; then export DEBIAN_FRONTEND=readline; fi
  - if [[ "$FB" == "2.1" ]]; then expect tests/ci/travis/dpkg_firebird2.1.exp; fi
  - if [[ "$FB" == "2.1" ]]; then export DEBIAN_FRONTEND=dialog; fi
  - if [[ "$FB" == "2.5" ]]; then export FIREBIRD_SERVER_CONFIG=/etc/default/firebird$FB; fi
  - if [[ "$FB" == "2.5" ]]; then sudo sed /ENABLE_FIREBIRD_SERVER=/s/no/yes/ -i $FIREBIRD_SERVER_CONFIG; fi
  - if [[ "$FB" == "2.5" ]]; then cat $FIREBIRD_SERVER_CONFIG | grep ENABLE_FIREBIRD_SERVER; fi
  - sudo service firebird$FB-super start
  - export URL_SVN_EXT=https://github.com/php/php-src/branches/PHP-$(phpenv version-name)/ext/pdo_firebird
  - if [[ $(phpenv version-name) == "7.0" ]]; then export URL_SVN_EXT="https://github.com/php/php-src/branches/PHP-7.0.0/ext/pdo_firebird"; fi
  - if [[ $(phpenv version-name) == "nightly" ]]; then export URL_SVN_EXT="https://github.com/php/php-src/trunk/ext/pdo_firebird"; fi
  - svn export $URL_SVN_EXT pdo_firebird -q
  - (cd pdo_firebird/; phpize && ./configure && make && sudo make install)

install:
  - echo "extension=pdo_firebird.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.0.0" --prefer-dist --no-interaction
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  # show some versions and env information
  - isql-fb -z -q -i /dev/null
  # initialize databases
  - echo "CREATE DATABASE 'localhost:/tmp/TEST.FDB' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 16384 DEFAULT CHARACTER SET UTF8;" > /tmp/create_test.sql
  - isql-fb -i /tmp/create_test.sql
  - cat /tmp/create_test.sql

script:
  - phpunit
